spring:
  config:
    import: classpath:generator-config.properties
  datasource:
    url: jdbc:mysql://localhost:3306/dev_cloud_disks_v100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver